name: SchematicBrushReborn
version: 0.1-BETA
api-version: "1.13"
depend:
  - "WorldEdit"
main: de.eldoria.schematicbrush.SchematicBrushReborn
authors: [Hadde, SirYwell]
commands:
  schematicbrush:
    description: Create a new schematic brush
    aliases:
      - sbr
      - sbra
      - schbr
      - schbra
  schematicbrushappend:
    description: Append a schematic set to a schematic brush
    aliases:
      - sbra
      - schbra
      - schematicbrushappend
  schematicpreset:
    description: Create or edit schematic brush presets
    aliases:
      - schpre