name: SchematicBrushReborn
version: 0.1-BETA
api-version: "1.13"
depend:
  - "WorldEdit"
main: de.eldoria.schematicbrush.SchematicBrushReborn
authors: [Hadde, SirYwell]
commands:
  schematicbrush:
    description: Create a new schematic brush
    aliases:
      - sbr
      - schbr
  schematicbrushmodify:
    description: Modify a schematic brush
    aliases:
      - sbrm
      - schbrm
  schematicbrushpreset:
    description: Create or edit schematic brush presets
    aliases:
      - sbrp
      - schbrpre