name: SchematicBrushReborn
version: 0.1-BETA
api-version: "1.13"
depend:
  - "WorldEdit"
main: de.eldoria.schematicbrush.SchematicBrushReborn
authors: [Hadde, SirYwell]
website: ""
commands:
  schematicbrushadmin:
    description: Manage schematic brush
    aliases:
      - sbra
      - schbra
  schematicbrush:
    description: Create a new schematic brush
    aliases:
      - sbr
      - schbr
  schematicbrushmodify:
    description: Modify a schematic brush
    aliases:
      - sbrm
      - schbrm
  schematicbrushpreset:
    description: Create or edit schematic brush presets
    aliases:
      - sbrp
      - schbrpre

permissions:
  schematicbrush.*:
    description: "Allows full access to all schematic brush commands"
  schematicbrush.brush.use:
    description: "Allows usage of schematic brushes"
  schematicbrush.preset.save:
    description: "Allows to save presets"
  schematicbrush.preset.modify:
    description: "Allows to modify existing presets"
  schematicbrush.preset.remove:
    description: "Allows to remove presets"
  schematicbrush.preset.info:
    description: "Allows to get information about a preset"
  schematicbrush.reload:
    description: "Allows to reload the plugin"
  schematicbrush.reloadschematics:
    description: "Allows to reload the schematic cache"
