name: Javadocs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Build Javadocs
        run: |
          echo "Building javadocs with gradle"
          ./gradlew clean schematicbrushreborn-api:javadoc
          echo "Moving to javadocs directory:"
          cd schematicbrushreborn-api/build/docs/javadoc
          echo "Creating .nojekyll to have Github pages deploy html as is:"
          touch .nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: schematicbrushreborn-api/build/docs/javadoc # The folder the action should deploy.
